In [1]:
import pandas as pd
import numpy as np

In [2]:
r_cols=['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
movie_dataset=pd.read_csv('ml-100k/u.item',sep='|',names=r_cols,encoding='latin-1')

In [3]:
movie_vector=movie_dataset[['Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

In [4]:
movie_vector.index=range(1,1683)
movie_vector=movie_vector.T
movie_vector

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
Action,0,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Adventure,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Animation,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Children's,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Comedy,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
Crime,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documentary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Drama,0,0,0,1,1,1,1,1,1,1,...,0,1,1,1,1,1,0,1,0,1
Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Film-Noir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Horror,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Musical,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
Sci-Fi,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Thriller,0,1,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
War,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
r_cols=['userID','movieID','ratings','timestamp']
user_dataset=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')
user_dataset

       userID  movieID  ratings  timestamp
0         196      242        3  881250949
1         186      302        3  891717742
2          22      377        1  878887116
3         244       51        2  880606923
4         166      346        1  886397596
...       ...      ...      ...        ...
99995     880      476        3  880175444
99996     716      204        5  879795543
99997     276     1090        1  874795795
99998      13      225        2  882399156
99999      12      203        3  879959583

[100000 rows x 4 columns]

In [6]:
user_vector=[]
for user in range(1,944):
    specuser_movieid=user_dataset[user_dataset['userID']==user][['movieID']] #Extracts movieID column and specuser_movieis also becomes dataframe with movieID column
    user_spec=[]
    for movieid in specuser_movieid['movieID']:
        user_spec.append(movie_vector[movieid].values)
    user_specdf=pd.DataFrame(user_spec,columns=range(1,19))
    user_specdf
    user_vec=[]                   
    for moviecategory in range(1,19):
        sum_val=sum(user_specdf[moviecategory])
        user_vec.append(sum_val/len(user_specdf))
    user_vector.append(user_vec)
user_vectdf=pd.DataFrame(user_vector)
user_vectdf

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.275735,0.154412,0.044118,0.091912,0.334559,0.091912,0.018382,0.393382,0.007353,0.003676,0.047794,0.047794,0.018382,0.161765,0.158088,0.191176,0.091912,0.022059
1,0.161290,0.048387,0.016129,0.064516,0.258065,0.145161,0.000000,0.564516,0.016129,0.032258,0.032258,0.016129,0.064516,0.258065,0.064516,0.193548,0.048387,0.000000
2,0.259259,0.074074,0.000000,0.000000,0.222222,0.185185,0.018519,0.407407,0.000000,0.037037,0.092593,0.037037,0.203704,0.092593,0.148148,0.388889,0.092593,0.000000
3,0.333333,0.166667,0.000000,0.000000,0.166667,0.166667,0.041667,0.250000,0.000000,0.000000,0.041667,0.041667,0.208333,0.125000,0.250000,0.458333,0.083333,0.000000
4,0.320000,0.188571,0.080000,0.165714,0.468571,0.051429,0.000000,0.154286,0.011429,0.005714,0.160000,0.068571,0.017143,0.108571,0.188571,0.108571,0.080000,0.011429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.367347,0.204082,0.020408,0.020408,0.306122,0.061224,0.000000,0.367347,0.020408,0.000000,0.020408,0.020408,0.020408,0.204082,0.163265,0.244898,0.061224,0.000000
939,0.214953,0.112150,0.018692,0.046729,0.392523,0.065421,0.000000,0.448598,0.000000,0.028037,0.037383,0.065421,0.028037,0.224299,0.177570,0.186916,0.140187,0.000000
940,0.454545,0.318182,0.136364,0.090909,0.318182,0.045455,0.000000,0.227273,0.000000,0.000000,0.000000,0.045455,0.045455,0.045455,0.363636,0.318182,0.045455,0.000000
941,0.227848,0.139241,0.050633,0.164557,0.278481,0.000000,0.000000,0.392405,0.025316,0.012658,0.037975,0.063291,0.113924,0.215190,0.075949,0.253165,0.126582,0.037975
942,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.000000,0.339286,0.011905,0.000000,0.083333,0.023810,0.017857,0.196429,0.130952,0.208333,0.089286,0.053571

In [7]:
user_vectdf.shape

(943, 18)

In [8]:
movie_vector.shape

(18, 1682)

In [9]:
content_vector=np.dot(user_vectdf,movie_vector)
content_vector

array([[0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235],
       [0.33870968, 0.40322581, 0.19354839, ..., 0.82258065, 0.25806452,
        0.56451613],
       [0.22222222, 0.72222222, 0.38888889, ..., 0.5       , 0.22222222,
        0.40740741],
       ...,
       [0.54545455, 1.09090909, 0.31818182, ..., 0.27272727, 0.31818182,
        0.22727273],
       [0.49367089, 0.62025316, 0.25316456, ..., 0.60759494, 0.27848101,
        0.39240506],
       [0.39880952, 0.79761905, 0.20833333, ..., 0.53571429, 0.33333333,
        0.33928571]])

In [10]:
content_vectors=pd.DataFrame(content_vector)
content_vectors=content_vectors.T
content_vectors

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,0.470588,0.338710,0.222222,0.166667,0.714286,0.454976,0.339950,0.220339,0.272727,0.336957,...,0.482759,0.282051,0.373239,0.375,0.518519,0.346939,0.457944,0.545455,0.493671,0.398810
1,0.621324,0.403226,0.722222,0.958333,0.617143,0.336493,0.570720,1.254237,0.545455,0.396739,...,0.482759,0.871795,0.478873,0.325,0.777778,0.816327,0.514019,1.090909,0.620253,0.797619
2,0.191176,0.193548,0.388889,0.458333,0.108571,0.113744,0.191067,0.305085,0.227273,0.184783,...,0.120690,0.282051,0.197183,0.100,0.296296,0.244898,0.186916,0.318182,0.253165,0.208333
3,1.003676,0.983871,0.888889,0.750000,0.942857,0.924171,0.816377,1.118644,0.954545,0.831522,...,0.971264,1.076923,1.007042,1.075,0.990741,1.040816,1.056075,1.000000,0.898734,1.053571
4,0.676471,0.903226,0.981481,0.875000,0.314286,0.672986,0.632754,0.745763,0.727273,0.711957,...,0.563218,0.820513,0.767606,0.775,0.648148,0.673469,0.700935,0.590909,0.645570,0.654762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286
1678,0.352941,0.451613,0.481481,0.583333,0.217143,0.308057,0.330025,0.423729,0.590909,0.380435,...,0.327586,0.589744,0.415493,0.325,0.490741,0.448980,0.411215,0.363636,0.468354,0.404762
1679,0.555147,0.822581,0.500000,0.375000,0.262857,0.687204,0.501241,0.406780,0.863636,0.635870,...,0.597701,0.769231,0.697183,0.850,0.490741,0.571429,0.672897,0.272727,0.607595,0.535714
1680,0.334559,0.258065,0.222222,0.166667,0.468571,0.312796,0.218362,0.169492,0.272727,0.255435,...,0.362069,0.230769,0.338028,0.300,0.370370,0.306122,0.392523,0.318182,0.278481,0.333333
1681,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286

In [13]:
#getting the movies watched by specfic user thatis movie id's
user_watched=user_dataset[user_dataset['userID']==4]['movieID'] #now movieID's will extracted as series not as dataframe because single bracket[] not[[]]
user_watched

1250     264
1329     303
2204     361
2526     357
3277     260
5960     356
12151    294
13893    288
16305     50
18930    354
20082    271
20383    300
24519    328
24743    258
24866    210
35313    329
48826     11
51203    327
64091    324
68273    359
71055    362
76722    358
86815    360
88891    301
Name: movieID, dtype: int64

In [17]:
spec_val=content_vectors[content_vectors[4]>(content_vectors[4].max()-0.3)][2]  
spec_val

16      1.148148
20      0.981481
28      0.740741
109     0.648148
171     1.074074
172     0.648148
183     0.796296
200     0.648148
230     0.740741
234     0.722222
256     0.703704
384     0.648148
559     0.537037
1109    0.666667
Name: 2, dtype: float64

In [16]:
recommended_movies=[]
for movieid in spec_val.index:
    if movieid in user_watched:
        pass
    else:
        recommended_movies.append(movieid)
recommended_movies

[16, 20, 28, 109, 171, 172, 183, 200, 230, 234, 256, 384, 559, 1109]